// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables. Please check your .env file.');
  console.error('Required variables: VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY');
  console.error('Current values:', {
    url: SUPABASE_URL ? 'Set' : 'Missing',
    key: SUPABASE_PUBLISHABLE_KEY ? 'Set (length: ' + SUPABASE_PUBLISHABLE_KEY.length + ')' : 'Missing'
  });
} else {
  // Log key info for debugging (first 20 chars only for security)
  const keyPreview = SUPABASE_PUBLISHABLE_KEY.substring(0, 20);
  const keyLength = SUPABASE_PUBLISHABLE_KEY.length;
  const isAnonKey = SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ') || SUPABASE_PUBLISHABLE_KEY.startsWith('sb_publishable_');
  const isServiceRole = SUPABASE_PUBLISHABLE_KEY.includes('service_role') || SUPABASE_PUBLISHABLE_KEY.startsWith('sb_service_');
  
  console.log('Supabase client initialized:', {
    url: SUPABASE_URL,
    keyPreview: keyPreview + '...',
    keyLength: keyLength,
    isAnonKey: isAnonKey,
    isServiceRole: isServiceRole,
    keyFormat: SUPABASE_PUBLISHABLE_KEY.startsWith('sb_publishable_') ? 'new format (sb_publishable_)' : 
               SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ') ? 'old format (JWT)' : 'unknown'
  });
  
  // Warn if it looks like service_role key
  if (isServiceRole) {
    console.error('⚠️ WARNING: This looks like a service_role key! Use the anon public key instead.');
    console.error('Get the correct key from: Supabase Dashboard → Settings → API → anon public');
  }
  
  // Confirm if it's the correct anon key
  if (isAnonKey && !isServiceRole) {
    console.log('✅ Using correct anon public key');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || '', 
  SUPABASE_PUBLISHABLE_KEY || '', 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY || '',
      },
    },
  }
);